# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
